### ISSUE TITLE
Undescriptive README

### ISSUE THREAD

**Issue by zeroeightysix** [tmpim/amulet#137]
Is it possible that the README can also include things like installation, a "hello world"-like example, etc?
Currently it's a little bare.

**Comment by Lemmmy** [comment]
https://amulet.squiddev.cc/

**Comment by SquidDev** [comment]
Honestly, at this point I'm fine with it being as nondescript as possible. Amulet is a _long_ way from usable, so I don't really want to encourage people to start using it quite yet.

**Comment by hugeblank** [comment]
I mean you could at least put the link to that site in the description of the repo, that would be a sufficient middle ground imo.

**Comment by Lemmmy** [comment]
I think once the site and Amulet are both ready, they could probably put it here:

![](https://shitty.download/SmbC.png)

**Comment by zardyh** [comment]
Amulet is not even close to being beta quality software. When it is, expect more of a description.
