### ISSUE TITLE
Clarify relationship with Lua

### ISSUE THREAD

**Issue by jameshaydon** [tmpim/amulet#144]
Currently, `amulet` produces Lua code. Is this an implementation detail? Or is `amulet`'s goal specifically to compile to Lua and be compatible with the Lua ecosystem?

**Comment by SquidDev** [comment]
I'm going to be honest, I'm don't think we're 100% sure. At the moment Amulet is very much in a "let's see where this takes us" stage - it's a language I want to use for real projects, but at the same time it's very much an opportunity for us to learn and play around with new concepts.

While Amulet will always generate Lua code (though I have vaguely looked into other backends), integrating with existing Lua code won't be painless. You'll need to define types for any external module you work with, which obviously raises the effort required compared with other Lua targetting languages like Fennel or Moonscript.

**Comment by SquidDev** [comment]
I'm going to close, as I don't think there's anything else we can do for now. Do comment if you have any further questions.

**Comment by jameshaydon** [comment]
:+1: Thanks for the explanation! Very interesting project.
