### ISSUE TITLE
Casting between ints and floats (and the reverse)

### ISSUE THREAD

**Issue by hugeblank** [tmpim/amulet#179]
Relevant discord comment from matheus, when asking about casting:
<img width="726" alt="image" src="https://user-images.githubusercontent.com/16393543/66444902-d91a0380-e9f9-11e9-992b-adeed81a42c2.png">

Since the only primitives are ints and floats (as far as I'm aware), it would be really interesting to consolidate the functionality to a single 'cast' call, that just checks if the value is a float or an int, and then flips it to an int or float, respectively.

**Comment by zardyh** [comment]
> Since the only primitives are ints and floats (as far as I'm aware), it would be really interesting to consolidate the functionality to a single 'cast' call, that just checks if the value is a float or an int, and then flips it to an int or float, respectively.

Unfortunately this isn't doable with our type system. (Well, it might be, but the type checking overhead + chance to get it wrong just isn't worth it.)

**Comment by zardyh** [comment]
I've compiled a list of all the user-facing builtins [here](https://hydraz.semi.works/amulet/99-builtins.html), btw.
