### ISSUE TITLE
Newtype optimisation broken in the REPL

### ISSUE THREAD

**Issue by zardyh** [tmpim/amulet#196]
Load this file then try matching on `x`—You can't. The pattern won't be lowered to a cast and we'll try to index a string.

```ocaml
type foo = Foo of string

let x = Foo "foo"
```

**Comment by zardyh** [comment]
bbb303cd42 disables newtype opt in the repl but we still need to address it.

**Comment by zardyh** [comment]
Of course a possible solution is just stating that newtype optimisation isn't guaranteed to run.

**Comment by SquidDev** [comment]
Yeah, this is something I've been thinking about for a while - if we ever start running the optimiser before linking modules together (which we should), then we need to think about this. 

I think the only correct thing to do here is to implement the optimisation as part of lowering. Unlike other optimisations, it actually changes the signature (and sometimes semantics) of the module, so I think this is our only option. We'd then effectively store a "type representation" flag within the `LowerState`, and use that to guide lowering of other modules. 

This is obviously going to make pattern lowering even more ugly, but I think it's the best losution.
