### ISSUE TITLE
Integers not closed under division

### ISSUE THREAD

**Issue by zardyh** [tmpim/amulet#86]
The type of `(/)`, `int -> int -> int`, seems to imply that the field of integers is closed under division.

It's not.
```
> 5 / 2
_ : int = 2.5
```

Proposed fixes:
- [ ] Round the result of `(/)` towards..
  - [ ] The nearest whole integer
  - [ ] Zero
  - [ ] INT_MIN
  - [ ] INT_MAX
- [ ] Make `(/) : int -> int -> float`

The lattermost of these seems to be the most general, as the user (or us, when there are libraries) can make any of the following the following, provided that all the rounding operations take `float`s to `int`s. 

```ocaml
let x // y = truncate (x / y)
let x // y = ceil (x / y)
let x // y = floor (x / y)
```

**Comment by SquidDev** [comment]
I think the second of those would be preferred. Then define `\\` as `truncate`.
